export const components = [
  {
    id: 'nose',
    name: '机首与驾驶舱',
    en: 'NOSE & FLIGHT DECK',
    code: 'ATA 53-10',
    material: 'CFRP / 铝合金',
    health: 99.8,
    mass: '4,280',
    count: 186,
    stress: 32.6,
    temperature: 23.8,
    description: '气动整流罩与驾驶舱结构，集成雷达罩、风挡及前压力隔框。',
    icon: 'cockpit',
  },
  {
    id: 'fuselage',
    name: '复合材料机身',
    en: 'COMPOSITE FUSELAGE',
    code: 'ATA 53-00',
    material: '碳纤维增强复合材料',
    health: 99.6,
    mass: '19,420',
    count: 428,
    stress: 46.2,
    temperature: 24.6,
    description: '连续碳纤维复合材料筒段，纵向桁条与环形框共同构成轻质承压结构。',
    icon: 'body',
  },
  {
    id: 'wing-left',
    name: '左翼总成',
    en: 'LEFT WING ASSEMBLY',
    code: 'ATA 57-10',
    material: 'CFRP / 钛合金',
    health: 99.4,
    mass: '8,650',
    count: 312,
    stress: 68.4,
    temperature: 21.2,
    description: '后掠复合材料机翼，包含中央翼盒、翼梁、翼肋及可变弯度后缘装置。',
    icon: 'wing',
  },
  {
    id: 'wing-right',
    name: '右翼总成',
    en: 'RIGHT WING ASSEMBLY',
    code: 'ATA 57-20',
    material: 'CFRP / 钛合金',
    health: 99.5,
    mass: '8,650',
    count: 312,
    stress: 67.8,
    temperature: 21.4,
    description: '大展弦比柔性机翼与倾斜式翼梢，兼顾巡航气动效率与结构重量。',
    icon: 'wing',
  },
  {
    id: 'engine-left',
    name: '左侧发动机',
    en: 'GEnx-1B · ENGINE 01',
    code: 'ATA 71-10',
    material: '钛合金 / 镍基高温合金',
    health: 98.8,
    mass: '6,147',
    count: 264,
    stress: 52.1,
    temperature: 642,
    description: '高涵道比涡轮风扇发动机，复合材料风扇叶片与锯齿形尾缘短舱。',
    icon: 'engine',
  },
  {
    id: 'engine-right',
    name: '右侧发动机',
    en: 'GEnx-1B · ENGINE 02',
    code: 'ATA 71-20',
    material: '钛合金 / 镍基高温合金',
    health: 99.1,
    mass: '6,147',
    count: 264,
    stress: 51.6,
    temperature: 638,
    description: '独立的双转子动力系统，包含风扇、压气机、燃烧室、涡轮及尾喷管。',
    icon: 'engine',
  },
  {
    id: 'tail',
    name: '尾翼与尾段',
    en: 'EMPENNAGE',
    code: 'ATA 55-00',
    material: 'CFRP / 铝锂合金',
    health: 99.7,
    mass: '3,280',
    count: 156,
    stress: 28.3,
    temperature: 20.8,
    description: '垂直安定面、水平安定面与尾锥结构，提供纵向及方向稳定性。',
    icon: 'tail',
  },
  {
    id: 'cabin',
    name: '客舱与地板梁',
    en: 'CABIN & FLOOR BEAMS',
    code: 'ATA 25-00',
    material: '铝合金 / 蜂窝夹层',
    health: 99.9,
    mass: '12,640',
    count: 296,
    stress: 24.8,
    temperature: 24,
    description: '双通道客舱、座椅导轨与地板横梁，上层客舱与下层货舱分层布置。',
    icon: 'cabin',
  },
  {
    id: 'landing-gear',
    name: '起落架系统',
    en: 'LANDING GEAR',
    code: 'ATA 32-00',
    material: '超高强度钢 / 钛合金',
    health: 98.9,
    mass: '5,420',
    count: 184,
    stress: 74.6,
    temperature: 26.3,
    description: '前起落架与双主起落架，集成缓冲支柱、轮轴、制动器及收放机构。',
    icon: 'gear',
  },
];

export const materials = [
  { name: '复合材料', value: 50, color: '#73deca' },
  { name: '铝合金', value: 20, color: '#8daec6' },
  { name: '钛合金', value: 15, color: '#efc17e' },
  { name: '钢及其他', value: 15, color: '#67787e' },
];

export const strainData = Array.from({ length: 29 }, (_, i) => ({
  time: `14:${String(20 + i).padStart(2, '0')}`,
  left: Math.round((42 + Math.sin(i * 0.65) * 8 + Math.cos(i * 1.7) * 3) * 10) / 10,
  right: Math.round((32 + Math.sin(i * 0.62 + 0.8) * 6 + Math.cos(i * 1.5) * 2) * 10) / 10,
}));

export const events = [
  { time: '14:48:32', name: '全机结构完整性检测', code: 'STR-0001', state: '通过' },
  { time: '14:47:16', name: '左翼应变传感器校准', code: 'SNS-0428', state: '完成' },
  { time: '14:45:08', name: '发动机振动数据同步', code: 'ENG-0071', state: '完成' },
];
