import { launchBrowser } from './browser.mjs';
import fs from 'node:fs/promises';
await fs.mkdir('output',{recursive:true});
const browser=await launchBrowser();
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});
page.on('pageerror',e=>console.log('PAGE ERROR:',e.message));
page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE ERROR:',m.text());});
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__ORBIT__?.ready || window.__ORBIT_ERROR__,{timeout:60000});
await page.locator('#loading').waitFor({state:'hidden',timeout:60000});
await page.screenshot({path:'output/preview-exploded.png'});
console.log(await page.evaluate(()=>({ready:window.__ORBIT__?.ready,error:window.__ORBIT_ERROR__,render:window.__ORBIT__?.renderer.info.render,parts:window.__ORBIT__?.washer.parts.length})));
await page.locator('[data-view="assembled"]').click();
await page.waitForFunction(()=>window.__ORBIT__.state.explosion<.02);
await page.screenshot({path:'output/preview-assembled.png'});
await page.locator('[data-view="cutaway"]').click();
await page.waitForFunction(()=>Math.abs(window.__ORBIT__.state.explosion-18)<.02);
await page.screenshot({path:'output/preview-cutaway.png'});
await page.locator('[data-view="thermal"]').click();
await page.waitForFunction(()=>Math.abs(window.__ORBIT__.state.explosion-25)<.02);
await page.screenshot({path:'output/preview-thermal.png'});
await browser.close();
